/** Tailwind utility bundles — edit here, not CSS files */
window.TW = {
  actionGrid: "grid grid-cols-2 gap-2 mt-2.5",
  activeChatIcon: "bg-brand text-brand-ink font-bold text-base",
  activeChatItem: "border-l-4 border-brand",
  activeMatchBadge: "text-[11px] font-semibold rounded-full px-2 py-0.5 whitespace-nowrap shrink-0",
  adjustRow: "flex gap-1.5 flex-wrap mt-2",
  agentClarifyCard: "bg-white border-2 border-brand rounded-2xl p-3.5 mb-3 shadow-card",
  agentMemoryCard: "border-2 border-brand/60 bg-white",
  agentMemoryDot: "w-3 h-3 rounded-full bg-ok shrink-0",
  agentMemoryGrid: "grid gap-1.5",
  agentMemoryLabel: "text-muted font-semibold shrink-0 w-[72px]",
  agentMemoryNotice: "mt-3 text-[12px] font-semibold rounded-xl px-3 py-2",
  agentMemoryRow: "flex items-start gap-2 text-[13px]",
  agentMemoryVal: "text-ink",
  aiState: "grid items-center gap-2.5",
  aiStep: "grid items-center gap-2.5 text-muted",
  aiSteps: "grid gap-2.5",
  analyzingDot: "w-4 h-4 rounded-full bg-ok",
  appHeader: "sticky top-0 z-30 bg-wash px-3 pt-2 pb-3",
  appLogo: "flex items-center gap-2.5 min-w-0 no-underline text-inherit",
  avatar: "w-[54px] h-[54px] rounded-full grid place-items-center bg-brand text-white text-lg font-medium",
  backTextBtn: "bg-transparent border-0 text-muted font-medium text-sm cursor-pointer whitespace-nowrap",
  bottomNav: "fixed bottom-0 h-[58px] bg-white border-t border-line grid grid-cols-4 z-20 w-full max-w-[430px] pb-[env(safe-area-inset-bottom)]",
  breakdown: "grid grid-cols-3 gap-2 my-3",
  candidateHead: "grid items-start gap-2",
  candidateMetrics: "flex gap-1.5 flex-wrap mt-2",
  candidateReason: "text-xs text-muted leading-relaxed mt-1.5",
  card: "bg-white border-0 rounded-[18px] p-4 mb-3 shadow-card mx-3",
  categoryChipsRow: "flex gap-2 overflow-x-auto pb-1.5",
  chatComposer: "grid gap-2 mt-2.5",
  chatPageHeader: "px-4 pt-4 pb-2",
  chatProfile: "grid items-center gap-3",
  chipCount: "inline-block ml-1 bg-black/6 rounded-full text-[10px] px-1.5 py-px font-medium align-middle",
  circleAdLine: "text-[13px] text-ink/75 italic mt-2 leading-snug",
  circleCard: "w-full text-left bg-white rounded-2xl p-3.5 border-2 border-transparent shadow-card transition-colors",
  circleCardHead: "flex items-start gap-3",
  circleCardIcon: "w-11 h-11 rounded-xl grid place-items-center text-base font-black shrink-0",
  circleCardStats: "flex gap-3 mt-2.5 text-[12px] text-muted",
  circleDemandIcon: "w-9 h-9 rounded-xl bg-[#FFF4ED] grid place-items-center text-lg shrink-0",
  circleHero: "rounded-2xl p-4 mt-3 mb-3 text-left",
  circleHotBody: "p-2.5",
  circleHotCard: "shrink-0 w-[132px] snap-start rounded-2xl overflow-hidden bg-white shadow-card text-left border-0 p-0",
  circleHotCover: "h-[72px] bg-cover bg-center",
  circleHotScroll: "flex gap-2.5 overflow-x-auto pb-2 mt-2 snap-x",
  circleInspire: "text-left rounded-2xl p-3.5 border-2 border-line bg-white w-full",
  circleInspireGrid: "grid gap-2 mt-2",
  circleList: "grid gap-2.5 mt-2",
  circleLive: "mt-4",
  circleLiveAvatar: "w-9 h-9 rounded-full bg-brand text-brand-ink grid place-items-center font-bold text-sm shrink-0",
  circleLiveItem: "flex items-center gap-2.5 py-2.5 border-b border-line last:border-0",
  circleMiniMap: "relative h-[120px] rounded-xl mt-3 overflow-hidden bg-[#e8ecf0]",
  circleMoment: "bg-white rounded-2xl p-3 shadow-card text-left w-full border-0",
  circleMomentHead: "flex items-center gap-2 mb-1.5",
  circleMomentList: "grid gap-2 mt-2",
  circlePage: "fixed inset-0 z-[80] bg-wash flex flex-col",
  circlePageBody: "flex-1 overflow-y-auto px-3 pb-8",
  circlePageHeader: "flex items-center gap-2 px-3 py-3 bg-white border-b border-line shrink-0",
  circlePulseBar: "flex items-center justify-between gap-2 mt-2 text-[12px]",
  circleTag: "text-[11px] font-semibold rounded-full px-2.5 py-1 bg-white/80 text-ink/80",
  circleTagRow: "flex flex-wrap gap-1.5 mt-3",
  circleTimeChip: "flex-1 py-2.5 rounded-xl border-2 border-white/80 bg-white/60 text-center text-[12px] font-bold text-muted",
  circleTimeRow: "flex gap-2 mt-3",
  circleTrendBubble: "shrink-0 px-3 py-2 rounded-full bg-white border border-line text-[12px] font-semibold text-ink whitespace-nowrap",
  circleTrendScroll: "flex gap-2 overflow-x-auto pb-1 mt-2",
  circleVibeBar: "flex-1 h-1.5 rounded-full bg-white/70 overflow-hidden",
  circleVibeFill: "h-full rounded-full",
  circleVibeRow: "flex items-center gap-2 mt-2 text-[12px] text-muted",
  circleWeather: "inline-flex items-center gap-1.5 rounded-full bg-white/90 px-2.5 py-1 text-[11px] font-semibold text-ink/80",
  confirmRow: "flex gap-2 flex-wrap",
  confirmingBanner: "my-3 p-2.5 rounded-xl bg-slate-50 border border-slate-200 font-bold text-center",
  ctaDetailBtn: "bg-slate-50 border border-line rounded-xl text-[13px] font-extrabold text-muted cursor-pointer transition-colors",
  ctaMatchBtn: "bg-brand border-0 rounded-2xl px-4 font-bold text-[16px] text-brand-ink cursor-pointer shadow-btn",
  ctaNavBtn: "flex items-center justify-center bg-white border border-line rounded-xl text-[13px] font-medium text-ink no-underline cursor-pointer transition-colors",
  dcAvatar: "w-8 h-8 rounded-full bg-gray-900 text-white grid place-items-center font-extrabold text-sm flex-shrink-0",
  dealBar: "flex items-center gap-1.5 bg-slate-50 border border-slate-200 rounded-xl mb-3 text-[13px]",
  dealStrip: "bg-slate-50 border border-slate-200 rounded-xl p-2.5 my-2.5 leading-snug",
  dealTag: "inline-block bg-hot text-white text-[10px] font-bold rounded px-1.5 py-0.5 mr-1.5 align-middle",
  demandCard: "border border-line rounded-2xl p-2.5 min-w-[238px] bg-white flex gap-2.5 items-start",
  demandCarousel: "flex overflow-x-auto pt-0.5 pb-2",
  demandList: "grid gap-2 my-2.5",
  empty: "text-muted",
  eyebrow: "text-muted text-xs font-semibold",
  feedbackChip: "bg-gray-100 border border-gray-200 rounded-full text-[12px] font-semibold text-gray-600 cursor-pointer",
  feedbackRow: "flex items-center gap-1.5 flex-wrap mt-2",
  filterChip: "bg-surface border-muted/40",
  finalPlanCard: "my-3.5 border border-line rounded-xl overflow-hidden text-left",
  gcAvatar: "text-2xl",
  gcHeaderCard: "flex items-center gap-3",
  gcHeaderInfo: "flex items-center gap-2.5 flex-1 min-w-0",
  gcListBody: "flex-1 min-w-0",
  gcListIcon: "w-11 h-11 rounded-xl bg-surface border border-line grid place-items-center flex-shrink-0",
  gcListTime: "text-[11px] text-muted whitespace-nowrap mt-0.5",
  groupListItem: "flex items-start gap-3 cursor-pointer transition-colors",
  headerAction: "text-xs font-semibold text-muted bg-white border border-line rounded-full px-3 py-1.5",
  headerTop: "flex items-center justify-between mb-2.5 gap-2",
  healthList: "grid gap-2 mt-3",
  intentAnalysisGrid: "grid gap-1.5 mt-2",
  intentRow: "flex gap-2 text-[13px]",
  intentRowLabel: "text-muted font-semibold shrink-0 w-[60px]",
  intentTag: "bg-surface rounded-full text-ink text-xs font-semibold",
  intentTags: "flex flex-wrap gap-1.5 mb-2.5",
  locChev: "text-muted text-lg leading-none shrink-0",
  locCopy: "flex-1 min-w-0",
  locPin: "w-9 h-9 rounded-xl bg-brand grid place-items-center shrink-0",
  locationPill: "w-full flex items-center gap-2.5 bg-white rounded-2xl border border-line px-3.5 py-3 text-left shadow-card",
  logoMascot: "shrink-0 drop-shadow-sm",
  logoType: "flex flex-col min-w-0 leading-none",
  mapBlock: "mb-0 p-0 overflow-hidden",
  mapPageLayout: "mx-3",
  matchTop: "grid items-center gap-3",
  mchip: "bg-gray-100 rounded-full text-gray-700 text-[11px] font-extrabold",
  memoryChip: "text-[11px] font-semibold rounded-full px-2.5 py-1",
  merchantAddress: "text-xs text-muted leading-snug",
  merchantBlock: "relative z-[1] rounded-2xl overflow-hidden shadow-card mb-3.5",
  merchantChips: "flex gap-1.5 flex-wrap mb-2.5",
  merchantCtaRow: "grid grid-cols-2 gap-2 mb-3.5",
  merchantDetailBody: "pt-3",
  merchantName: "text-xl",
  merchantRatingRow: "flex items-center gap-1 flex-wrap",
  message: "flex flex-col max-w-[78%] my-2.5",
  metaRow: "pb-2",
  modalActions: "grid grid-cols-2 gap-2.5",
  modalClose: "rounded-lg bg-transparent text-muted text-sm font-medium px-2 py-1",
  modalHeader: "flex justify-between items-center sticky top-0 bg-white z-[2] border-b border-line",
  modalInfo: "mt-1",
  modalInfoRow: "flex justify-between items-center border-b border-line text-sm",
  modalOverlay: "fixed inset-0 z-[60] flex items-end justify-center",
  modalSheet: "bg-white rounded-t-[20px] w-full max-w-[430px] max-h-[88vh] overflow-y-auto",
  navDot: "absolute top-0 right-[18%] bg-hot text-white rounded-full text-[9px] not-italic font-bold",
  navIcon: "w-7 h-7 grid place-items-center rounded-lg transition-colors",
  navItem: "bg-transparent text-muted text-[10px] font-semibold flex flex-col items-center justify-center gap-0.5 pt-1",
  noticeCard: "bg-brand/20 text-ink border border-brand/40 rounded-2xl p-3 mb-2.5 leading-normal text-[13px] font-medium",
  openBadge: "bg-ok/15 text-ok rounded-md text-[11px] font-bold",
  pctCell: "text-xs border-b border-line min-w-0 overflow-hidden whitespace-nowrap",
  pctGrid: "grid gap-0",
  pctHeaderCell: "font-extrabold text-center text-[13px]",
  pctRowLabel: "text-muted font-extrabold",
  phoneShell: "mx-auto min-h-screen bg-wash w-full max-w-[430px]",
  planCard: "sticky top-0 z-[8]",
  planCompareTable: "mb-2.5 overflow-x-auto",
  planLabelC: "text-ink/70",
  planLabelA: "text-ink/70",
  planLabelB: "text-ink/70",
  platformValue: "text-muted leading-relaxed mt-3.5",
  poiSheet: "px-4 pb-4 pt-3",
  primaryButton: "bg-brand text-brand-ink border-0 rounded-2xl px-4 font-bold text-[16px] shadow-btn",
  progressFill: "h-full bg-brand rounded-full transition-all",
  progressTrack: "h-2.5 bg-line rounded-full overflow-hidden",
  quickReplies: "flex gap-2 overflow-x-auto pb-2",
  radiusChip: "flex-1 py-2 rounded-xl border-2 border-line bg-white text-center text-[13px] font-semibold text-muted",
  radiusRow: "flex gap-2 mt-3",
  rankBadge: "w-7 h-7 rounded-full grid place-items-center bg-gray-900 text-white text-xs font-extrabold",
  ratingNum: "text-[17px] font-black text-accent tabular-nums",
  ratingStar: "text-accent text-sm tracking-tight",
  replanBody: "grid gap-3",
  replanCandidate: "border border-line rounded-xl bg-white",
  replanCandidateList: "grid gap-2.5",
  replanContext: "bg-slate-50 border border-slate-200 rounded-xl",
  safetyButton: "bg-white border border-gray-300 rounded-xl text-[13px] font-extrabold text-gray-700 cursor-pointer w-full",
  sceneFilterHost: "flex flex-col gap-0 overflow-visible pb-1",
  sceneIcon: "inline-grid place-items-center rounded-[14px] text-[15px] font-black shrink-0",
  sceneNav: "shadow-sm",
  scoreCircle: "w-[66px] h-[66px] grid place-items-center rounded-full font-bold",
  scoreFormula: "bg-white border border-slate-200 rounded-lg text-slate-700 font-bold",
  secondaryButton: "bg-white border-2 border-line text-ink rounded-2xl px-4 font-bold",
  sectionHead: "flex items-center justify-between mb-3",
  sectionTitle: "flex items-center justify-between mb-2.5",
  sheetBuddyRow: "flex items-center justify-between my-2.5 mb-1",
  sheetMatch: "bg-hot text-white text-[11px] font-bold rounded-md whitespace-nowrap",
  sheetTitleRow: "flex items-center gap-2 flex-wrap mb-1",
  stars: "text-sm",
  statPill: "flex-shrink-0 snap-start bg-white rounded-2xl px-3.5 py-2.5 min-w-[88px] shadow-card",
  statStrip: "flex gap-2 overflow-x-auto pb-1 snap-x snap-mandatory",
  successCard: "text-center",
  successMark: "w-16 h-16 mx-auto mb-3 rounded-full grid place-items-center bg-ok text-white text-2xl font-black",
  successSecondaryRow: "grid grid-cols-3 gap-2 mt-2",
  systemMsg: "flex justify-center my-2.5",
  tagRow: "pt-2 pb-1",
  textButton: "bg-white border border-line rounded-lg px-3 py-2 font-medium whitespace-nowrap text-ink",
  toast: "fixed z-40 rounded-full text-white font-bold opacity-0 pointer-events-none transition-all bottom-[84px] left-1/2 -translate-x-1/2 max-w-[360px] bg-gray-900/90 px-3.5 py-2.5",
  toastShow: "opacity-100 translate-y-0",
  muted: "text-muted leading-relaxed",
  page: "hidden",
  pageActive: "block",
  verifiedBadge: "inline-block bg-surface text-muted border border-line rounded-full text-[10px] font-medium align-middle",
  waitChip: "bg-[#ececec] text-gray-700",
  waitChoiceRow: "border-t border-line pt-3",
  waitStatus: "my-2 text-muted font-extrabold",
  wantGoButton: "bg-white border border-gray-300 rounded-full text-xs font-bold text-gray-700 cursor-pointer whitespace-nowrap",
  whyDetails: "my-2 border border-line rounded-xl overflow-hidden",
  wide: "w-full",
  refDiscover: "py-3 px-4 pb-6",
  refMapBlock: "mb-3.5",
  refMapHeading: "mb-2",
  refMapChips: "flex gap-2 overflow-x-auto mb-2.5 pb-0.5 scrollbar-none",
  refMapChip: "shrink-0 min-h-8 px-3.5 border border-line rounded-full bg-white text-xs font-semibold text-[#666] cursor-pointer",
  refMapChipActive: "bg-[#FFC107] border-[#FFC107] text-brand-ink",
  refMapCard: "rounded-[22px] overflow-hidden shadow-card border border-line bg-white",
  refMapVisual: "relative h-80 overflow-hidden",
  refMapOverlay: "absolute inset-0 z-[12] pointer-events-none",
  refMapFooter: "absolute left-3 right-14 bottom-3 z-[14] flex items-center gap-2.5 py-2.5 px-3.5 rounded-2xl bg-white/95 border border-black/[0.06] shadow-[0_2px_12px_rgba(0,0,0,0.08)] pointer-events-none",
  refMapLocate: "absolute right-3 bottom-3 z-[15] w-10 h-10 border-0 rounded-full bg-white grid place-items-center cursor-pointer shadow-[0_2px_10px_rgba(0,0,0,0.12)]",
  refBubble: "absolute -translate-x-1/2 -translate-y-1/2 inline-flex items-center gap-1.5 py-[7px] px-3 rounded-full bg-white/95 border border-black/[0.06] shadow-sm text-xs font-bold text-brand-ink whitespace-nowrap cursor-pointer",
  refBubbleDot: "w-2 h-2 rounded-full shrink-0",
  refBubbleMeta: "text-[11px] font-semibold text-[#1A73E8]",
  refBubbleActive: "border-2 border-[#FFC107] shadow-[0_2px_12px_rgba(255,193,7,0.35)]",
  refPoiCard: "mt-3.5 bg-white rounded-[22px] shadow-card overflow-hidden border border-line",
  refPoiHero: "h-[200px] bg-[#B8D9F0] bg-center bg-cover bg-no-repeat",
  refPoiBody: "py-3.5 px-4 pb-[18px]",
  refPoiTitleRow: "flex items-start justify-between gap-2.5",
  refPoiOpen: "shrink-0 py-1 px-2.5 rounded-full bg-[#E6F4EA] text-[#137333] text-[11px] font-bold",
  refPoiRating: "mt-2 text-[13px] text-[#666]",
  refPoiStatus: "mt-2 mb-3.5 text-xs text-[#888] leading-snug",
  refPoiMetrics: "grid grid-cols-4 gap-2 mb-3.5",
  refPickCard: "rounded-[18px] overflow-hidden border border-[#E8F0FE] mb-3 bg-white",
  refPickTop: "flex items-center justify-between gap-2 py-3 px-3.5 pb-2.5 bg-gradient-to-br from-[#E8F4FC] to-[#D4E8F7]",
  refPickBadge: "inline-block py-1 px-2.5 rounded-full bg-white/90 text-[#1A73E8] text-xs font-extrabold",
  refPickForming: "text-[11px] font-bold text-[#1A73E8]",
  refOppGrid: "grid grid-cols-4 gap-2 py-3 px-3.5 pb-2",
  refOppList: "m-0 py-0 px-3.5 pb-2.5 pl-7 text-xs text-[#666] leading-snug list-disc",
  refPickTags: "flex flex-wrap gap-1.5 px-3.5 pb-3.5",
  refDealBar: "grid items-center gap-2.5 py-3 px-3.5 rounded-2xl bg-[#FAFAFA] mb-3.5 grid-cols-[auto_1fr_auto]",
  refDealIcon: "w-9 h-9 rounded-[10px] bg-[#FFC107] grid place-items-center text-sm font-extrabold text-brand-ink",
  refDealLink: "border-0 bg-transparent text-[#1A73E8] text-sm font-semibold cursor-pointer",
  refLiveHead: "flex items-center justify-between mb-2",
  refLiveRow: "grid items-center gap-2.5 w-full py-2.5 border-0 border-b border-[#F5F5F5] bg-transparent text-left cursor-pointer grid-cols-[44px_1fr_auto]",
  refLiveAvatar: "w-11 h-11 rounded-full bg-[#EEEEEE] grid place-items-center text-base font-extrabold text-[#555]",
  refLiveBody: "",
  refLiveJoin: "text-[#1A73E8] text-sm font-bold",
  refVerified: "inline-block ml-1 py-px px-1.5 rounded bg-[#F0F0F0] text-[10px] font-semibold text-[#666]",
  refPoiActions: "pt-4 mt-2 border-t border-[#F5F5F5]",
  refBtnPrimary: "w-full min-h-[52px] border-0 rounded-full bg-[#FFC107] text-brand-ink text-base font-extrabold cursor-pointer shadow-[0_6px_20px_rgba(255,193,7,0.4)] active:bg-[#E6AC00]",
  refBtnRow: "grid grid-cols-2 gap-2.5 mt-2.5",
  refBtnSecondary: "min-h-12 border-0 rounded-full bg-[#F5F5F5] text-brand-ink text-sm font-bold cursor-pointer",
  refRadiusRow: "flex gap-2 mb-3",
  radiusPill: "flex-1 min-h-10 text-xs font-semibold border border-line rounded-full bg-white text-ink/80 cursor-pointer",
  radiusPillActive: "bg-[#FFC107] border-[#FFC107] text-brand-ink shadow-[0_4px_14px_rgba(255,193,7,0.35)]",
  refStats: "grid grid-cols-2 gap-3 mb-1",
  statCard: "bg-white rounded-[20px] py-4 px-[18px] shadow-card border border-line",
  headerActions: "flex items-center gap-2 shrink-0",
  headerSearch: "w-9 h-9 border-0 rounded-full bg-white text-[#666] grid place-items-center cursor-pointer",
  headerLogin: "border-0 rounded-full bg-[#FFC107] text-brand-ink text-[13px] font-bold py-2 px-4 cursor-pointer",
  discoverHeaderExtras: "mt-2.5",
  // agent / scene (from legacy style.css)
  agentConsole: "grid gap-3.5",
  agentHead: "flex justify-between gap-3.5 items-start",
  agentStatus: "inline-flex items-center gap-1.5 py-2 px-2.5 border border-gray-200 rounded-full bg-white text-gray-600 text-xs whitespace-nowrap",
  agentInputShell: "border-[1.5px] border-gray-200 rounded-[18px] bg-[#fafafa] p-3 focus-within:border-[#ffd100] focus-within:shadow-[0_0_0_4px_rgba(255,209,0,0.18)]",
  agentSignalRow: "flex gap-1.5 flex-wrap mt-2",
  agentActions: "grid gap-2.5",
  agentToggle: "inline-flex w-max items-center gap-1.5 text-gray-500 text-xs",
  agentBriefGrid: "grid grid-cols-3 gap-2 mt-2.5",
  agentPrompts: "pb-0",
  agentQ: "text-sm font-bold text-ink mb-2",
  agentParseCard: "bg-white border-0 rounded-[18px] p-4 mb-3 shadow-card mx-3",
  aiCard: "bg-white border-0 rounded-[18px] p-4 mb-3 shadow-card mx-3",
  clarifyChip: "bg-brand/20 border border-brand/50 rounded-full px-3 py-1.5 text-[13px] font-semibold text-brand-ink cursor-pointer",
  clarifyChips: "flex flex-wrap gap-2",
  sceneGroupGrid: "grid grid-cols-5 gap-2 max-[380px]:grid-cols-3",
  sceneGroupTile: "flex flex-col items-center text-center gap-0.5 py-2.5 px-1.5 rounded-[14px] border-[1.5px] border-transparent",
  sceneSubPanel: "max-h-0 opacity-0 overflow-hidden transition-all duration-300",
  sceneSubPanelOpen: "max-h-[140px] opacity-100 mt-2.5",
  sceneSubTrack: "flex gap-2 overflow-x-auto pb-1",
  sceneSubChip: "shrink-0 flex items-center gap-2 py-2.5 px-3 rounded-[14px] border-[1.5px] border-gray-200 bg-white min-w-[128px]",
  sceneClearFilter: "w-full mt-2.5 py-2 border-0 bg-transparent text-gray-400 text-xs font-semibold underline",
  discoverFilterCard: "mt-3 py-3.5 px-3 rounded-[18px] bg-white shadow-card",
  discoverFilterNote: "my-0.5 mb-3 text-xs leading-snug",
  discoverControlLabel: "my-3 mb-2 text-gray-500 text-xs font-extrabold",
  discoverCircleList: "grid grid-cols-2 gap-2 max-[380px]:grid-cols-1",
  discoverCircleCard: "min-h-[74px] p-2.5 rounded-2xl shadow-none",
  discoverSceneGrid: "grid grid-cols-5 gap-2 max-[380px]:grid-cols-3",
  discoverPoiList: "grid gap-2 mt-2",
  discoverPoiRow: "w-full min-h-[62px] border border-gray-200 rounded-2xl bg-white p-2.5 grid grid-cols-[auto_1fr_auto] gap-2.5 items-center text-left hover:border-brand hover:shadow-[0_0_0_3px_rgba(255,224,51,0.22)]",
  emptyState: "p-3.5 border border-dashed border-gray-300 rounded-2xl bg-white text-gray-400 text-xs leading-snug",
  linkish: "text-xs font-semibold text-accent bg-transparent border-0 p-0 cursor-pointer",
  liveDot: "w-2 h-2 rounded-full bg-[#58cc02] shrink-0 animate-pulse",
  circleMeta: "text-xs text-muted mt-0.5",
  mapDemandRow: "w-full border border-[#ebebeb] rounded-[14px] bg-white p-2.5 grid grid-cols-[36px_1fr_auto] items-center gap-2.5 text-left cursor-pointer mb-1.5 hover:bg-[#fffdf0] hover:border-[#ffe033]",
  mapDemandAvatar: "w-9 h-9 rounded-full grid place-items-center bg-brand text-brand-ink text-[13px] font-black shrink-0",
  mapDemandBody: "min-w-0",
  mapDemandJoin: "text-accent text-xs font-extrabold whitespace-nowrap",
  profileHeroCard: "bg-white border-0 rounded-[18px] p-4 mb-3 shadow-card mx-3",
  profileHeroRow: "flex gap-3.5 items-center",
  profileAvatarLg: "w-14 h-14 rounded-full overflow-hidden bg-brand flex items-center justify-center font-bold text-[22px] shrink-0",
  profileStatsRow: "grid grid-cols-3 gap-2 mt-3.5 text-center text-xs",
  messagesCard: "min-h-[220px]",
  matchCard: "bg-white border-0 rounded-[18px] p-4 mb-3 shadow-card mx-3",
  placeMini: "bg-slate-50 border border-slate-200 rounded-xl p-2.5 my-2.5 leading-snug",
  planCopy: "bg-slate-50 border border-slate-200 rounded-xl p-2.5 my-2.5 leading-snug",
  dealBox: "bg-slate-50 border border-slate-200 rounded-xl p-2.5 my-2.5 leading-snug",
  dealRankCard: "bg-white border-0 rounded-[18px] p-4 mb-3 shadow-card mx-3",
  intentSummaryCard: "bg-surface border-0 rounded-2xl shadow-none mb-2 mx-0 py-3 px-3.5",
  timelineList: "m-0 pl-[18px] text-[13px] text-muted leading-loose",
  repBadge: "text-xs text-amber-800 bg-amber-50 py-0.5 px-1.5 rounded-md",
  repLg: "text-[13px] py-1 px-2.5",
  refMapDest: "absolute -translate-x-1/2 -translate-y-full z-[8] inline-flex items-center gap-1.5 py-1.5 px-3 rounded-full bg-white/95 border-2 border-[#FFC107] text-xs font-extrabold text-brand-ink whitespace-nowrap pointer-events-none shadow-[0_2px_12px_rgba(255,193,7,0.35)]",
  refMapDestDot: "w-2 h-2 rounded-full bg-[#FFC107]",
  sgLabel: "text-xs font-bold",
  sgMeta: "text-[9px] text-gray-400 font-medium",
  sscText: "",
};
